train:
  outputFolder: data/results/seta-resnet152

  # Eval 
  evalIndices: [10, 20, 30, 40]

  # Training params
  itPerEpoch: 1000
  epochs: 3
  lr: 0.0001
  lrDecay: 0.985
  betas: [0.9, 0.999]
  batchSize: 64

  data:
    folder: /data
    numWorkers: 4
    trainSet: A
    valSet: V

  model:
    backbone: resnet152
    nHidden: 256
    
  
  