train:
  outputFolder: data/results/setc-efficientnetb5

  # Eval 
  evalIndices: [4936, 6817, 9110, 9361, 6967, 2567]

  # Training params
  itPerEpoch: 1000
  epochs: 150
  lr: 0.0001
  lrDecay: 0.985
  betas: [0.9, 0.999]
  batchSize: 64

  data:
    folder: /data
    numWorkers: 4
    trainSet: C
    valSet: V

  model:
    backbone: efficientnet_b5
    nHidden: 256
    
  
  